### ISSUE TITLE
Error: Cannot create measurement

### ISSUE THREAD

**Issue by baocareos** [nuralogix/dfx-e2e-demo-python#5]
Hello,
In your step 9: Obtain a valid DFX license key, study ID and study configuration file (.dat) from NuraLogix.

What do you mean:
- study ID ?
- study configuration file (.dat) ?

I already successfully created a account (demo), I got the license_key.
When I launch the command python dfxexample.py:

python dfxexample.py --license_key here_is_my_license_key_obtained_from_dashboard.deepaffex.ai/ --study_id I_do_NOT_know_how_I_can_have_it_so_I_use_the_Study_Index_obtained_from_tab_Study_in_dashboard.deepaffex.ai --email my_email --password my_password --imageSrc absolute_path_to_your_demo_video_dfxDemoCP1.mov --study absolute_path_to_my_local_file_client.user_token

where in my local file client.user_token, I copy the User token that I get from the console (Indeed, I launch the above comment without --study, then I see this user token. I save it in client.user_token file and for the 2nd time, I pass it to the --study argument.

I get error:

{'Code': 'VALIDATION_ERROR', 'Errors': {'StudyID': ['INVALID_UUID']}, 'Message': ''}
Traceback (most recent call last):
  File "/home/qbdo/.virtualenvs/dfx/lib/python3.6/site-packages/dfxapiclient/simpleclient.py", line 264, in create_new_measurement
    self.measurement.create()
  File "/home/qbdo/.virtualenvs/dfx/lib/python3.6/site-packages/dfxapiclient/measurements.py", line 67, in create
    raise Exception("Cannot create measurement")
Exception: Cannot create measurement

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "dfxexample.py", line 537, in <module>
    loop.run_until_complete(main(args))
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "dfxexample.py", line 451, in main
    timeout=20)
  File "/usr/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "dfxexample.py", line 435, in _setup_apiclient
    client.create_new_measurement()
  File "/home/qbdo/.virtualenvs/dfx/lib/python3.6/site-packages/dfxapiclient/simpleclient.py", line 267, in create_new_measurement
    self.measurement.create()
  File "/home/qbdo/.virtualenvs/dfx/lib/python3.6/site-packages/dfxapiclient/measurements.py", line 67, in create
    raise Exception("Cannot create measurement")
Exception: Cannot create measurement

Please help !
Thanks !
Bao

**Comment by sambhare** [comment]
Hello 

Study ID - You can get this from the Dashboard:
* Sign into the dashboard
* Click on "Studies" on the left
* Click on "Details" for the study
* From the "Study Details" page use the "Study Index" as the study ID

Study configuration file - While this will eventually downloadable from the Dashboard, for now you can:
* download the C/C++ SDK from [here](https://deepaffex.ai/en/developers-sdk.html) (OS doesn't matter) 
* Use the .dat file from the res/models subfolder as the study configuration file

Do please let me know if that works for you and then I will close the issue.

**Comment by baocareos** [comment]
by the way, (I know that it is not good channel to discuss but...), on the site https://www.deepaffex.ai/en/developers-sdk.html, the sdk does NOT support Android.

How can I integrate your sdk in a Android smart phone then send the request to the cloud... ?
(can I use the Linux SDK version ?)
Thanks !
Bao

**Comment by sambhare** [comment]
Hello Bao

We are still working on Android and iOS SDKs and they are not ready yet. Please contact us directly using the Contact form on deepaffex.ai and we can discuss this offline.

Thanks

Rajas
