### ISSUE TITLE
Unable to create collector

### ISSUE THREAD

**Issue by KhushalGoyal** [nuralogix/dfx-e2e-demo-python#7]
While creating collector
```# Create collector
self._collector = self._dfxFactory.createCollector()
if self._collector.getCollectorState() == dfx.CollectorState.ERROR:
    print("Collector creation failed: {}".format(
        self._collector.getLastErrorMessage()))
    sys.exit(1)
print("Created collector")
```
Got an error like below, although I am passing the study configuration path as mentioned in the MD file
```This method initializes the DFX extractor by setting up the study, collector, and DFX API client. The study is initialized from a `.dat` file provided by `studyCfgPath`. The collector is set by calling `dfxFactory.createCollector()`.```

```From cffi callback <function dfx_string_callback_handler at 0x7fdd4a977378>:
Traceback (most recent call last):
  File "/home/DeepAffex/dfx-demo/lib/python3.6/site-packages/libdfx/_callbacks.py", line 42, in dfx_string_callback_handler
    ffi.from_handle(userData).append(ffi.string(string1).decode('ascii'))
UnicodeDecodeError: 'ascii' codec can't decode byte 0x81 in position 71: ordinal not in range(128)
```

**Comment by sambhare** [comment]
Which file did you pass as `studyCfgPath`? It should be named `generic-v7.dat` or something similar. It should *not* be `shape_predictor_68_face_landmarks.dat` - that is the face landmarks model for Dlib.

A sample study configuration file (.dat) can be obtained by downloading the DFX C++ Windows/macOS/Linux SDK from here, and is located in dfxsdk/res/models.

**Comment by KhushalGoyal** [comment]
Yes, @sambhare Thanks for the quick update. 
Thanks for the help I figured it out what I am doing wrong.
