### ISSUE TITLE
where could I find study file

### ISSUE THREAD

**Issue by MichaelZou1** [nuralogix/dfx-e2e-demo-python#8]
I'd like test dfx on my mac, and already registered one trial account on https://dashboard.deepaffex.cn/login; now I have study id  and  the  problem is where could I find the study file which is mandatory for dfxFactory

**Comment by sambhare** [comment]
A sample study configuration file (.dat) can be obtained by downloading the DFX C++ Windows/macOS/Linux SDK from https://deepaffex.cn/developers-sdk, and is located in the dfxsdk/res/models folder
